/* Quilldown service worker — makes the app work offline.
   • Everything listed in sw-assets.js is pre-cached on install (generated by `node tools/list-assets.mjs`).
   • ./vendor/* (libraries, fonts) is cache-first; the app's own files are stale-while-revalidate,
     so edits appear on the next load even if you forget to regenerate sw-assets.js.
   Service workers need https:// or http://localhost — they are simply skipped when opened from disk (file://),
   where the bundled ./vendor files already make the app work offline. */
importScripts('sw-assets.js');
const CACHE = 'quilldown-' + self.QUILLDOWN_VERSION;

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await Promise.allSettled(self.QUILLDOWN_ASSETS.map(url => cache.add(new Request(url, { cache: 'reload' }))));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if ((key.startsWith('quilldown-') || key.startsWith('inkdown-')) && key !== CACHE) await caches.delete(key);   // also caches from the old "Inkdown" name
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: true });
    const isVendor = url.pathname.includes('/vendor/');
    if (hit && isVendor) return hit;
    const network = fetch(req).then(res => { if (res && res.ok) cache.put(req, res.clone()); return res; });
    if (hit) { event.waitUntil(network.catch(() => {})); return hit; }
    try { return await network; }
    catch (err) {
      if (req.mode === 'navigate') { const shell = await cache.match('index.html', { ignoreSearch: true }); if (shell) return shell; }
      throw err;
    }
  })());
});
