/* Quilldown — downloads every third-party file the app uses into ./vendor so it runs fully offline.
   Run from the project root:   node tools/fetch-vendor.mjs
   Needs Node 18+ and an internet connection. Safe to re-run; bump versions below to upgrade,
   then bump CACHE in sw.js so installed copies refresh. */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const V = path.join(ROOT, 'vendor');
const CDN = 'https://cdn.jsdelivr.net';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const VERSIONS = { marked: '12.0.2', dompurify: '3.1.6', highlight: '11.10.0', katex: '0.16.11', mermaid: '11.4.0', docx: '8.5.0', html2canvas: '1.4.1', emojibase: '15.3.2' };

const get = async (url, opts = {}) => {
  const r = await fetch(url, { headers: { 'User-Agent': UA }, ...opts });
  if (!r.ok) throw new Error(url + ' → ' + r.status);
  return r;
};
const save = async (rel, data) => { const p = path.join(V, rel); await mkdir(path.dirname(p), { recursive: true }); await writeFile(p, data); console.log('  ✓', rel, (data.length / 1024).toFixed(0) + ' KB'); };
const fetchTo = async (url, rel) => save(rel, Buffer.from(await (await get(url)).arrayBuffer()));

console.log('Libraries');
await fetchTo(`${CDN}/npm/marked@${VERSIONS.marked}/marked.min.js`, 'marked.min.js');
await fetchTo(`${CDN}/npm/dompurify@${VERSIONS.dompurify}/dist/purify.min.js`, 'purify.min.js');
await fetchTo(`${CDN}/gh/highlightjs/cdn-release@${VERSIONS.highlight}/build/highlight.min.js`, 'highlight.min.js');
await fetchTo(`${CDN}/npm/katex@${VERSIONS.katex}/dist/katex.min.js`, 'katex/katex.min.js');
await fetchTo(`${CDN}/npm/mermaid@${VERSIONS.mermaid}/dist/mermaid.min.js`, 'mermaid.min.js');
await fetchTo(`${CDN}/npm/docx@${VERSIONS.docx}/build/index.umd.js`, 'docx.umd.js');
await fetchTo(`${CDN}/npm/html2canvas@${VERSIONS.html2canvas}/dist/html2canvas.min.js`, 'html2canvas.min.js');

console.log('KaTeX stylesheet + fonts (woff2 only)');
let kcss = await (await get(`${CDN}/npm/katex@${VERSIONS.katex}/dist/katex.min.css`)).text();
const kfonts = new Set();
kcss = kcss.replace(/src:([^;}]+)/g, (m, src) => {
  const w2 = /url\((fonts\/[^)]+\.woff2)\)\s*format\("woff2"\)/.exec(src);
  if (!w2) return m;
  kfonts.add(w2[1]);
  return 'src:url(' + w2[1] + ') format("woff2")';
});
await save('katex/katex.min.css', Buffer.from(kcss));
for (const f of kfonts) await fetchTo(`${CDN}/npm/katex@${VERSIONS.katex}/dist/${f}`, 'katex/' + f);

console.log('App fonts (latin + latin-ext)');
const gf = await (await get('https://fonts.googleapis.com/css2?family=Inter:wght@400;450;500;600;700&family=Instrument+Serif:ital@0;1&family=JetBrains+Mono:wght@400;500&display=swap')).text();
const blocks = [...gf.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g)].filter(b => b[1] === 'latin' || b[1] === 'latin-ext');
const seen = new Map(); let fontsCss = '/* Generated by tools/fetch-vendor.mjs — local copies of the Google Fonts used by the app. */\n';
for (const [, subset, block] of blocks) {
  const url = /url\((https:[^)]+)\)/.exec(block)[1];
  if (!seen.has(url)) {
    const family = /font-family:\s*'([^']+)'/.exec(block)[1].replace(/\s+/g, '-').toLowerCase();
    const name = `${family}-${subset}-${seen.size}.woff2`;
    seen.set(url, name);
    await fetchTo(url, 'fonts/' + name);
  }
  fontsCss += `/* ${subset} */\n` + block.replace(/url\(https:[^)]+\)/, `url(${seen.get(url)})`) + '\n';
}
await save('fonts/fonts.css', Buffer.from(fontsCss));

console.log('Emoji data');
const raw = await (await get(`${CDN}/npm/emojibase-data@${VERSIONS.emojibase}/en/data.json`)).json();
const sc = async name => (await get(`${CDN}/npm/emojibase-data@${VERSIONS.emojibase}/en/shortcodes/${name}.json`)).json();
const [scGithub, scIamcal] = [await sc('github'), await sc('iamcal')];
const codesFor = hex => [...new Set([].concat(scGithub[hex] || [], scIamcal[hex] || []))].map(s => s.toLowerCase());
const GROUPS = ['Smileys & emotion', 'People & body', null, 'Animals & nature', 'Food & drink', 'Travel & places', 'Activities', 'Objects', 'Symbols', 'Flags'];
const list = raw.filter(e => GROUPS[e.group] && e.version <= 15).sort((a, b) => a.order - b.order).map(e => {
  const o = [e.emoji, e.label, (e.tags || []).join(' '), e.group, codesFor(e.hexcode).join(' ')];
  if (e.skins && e.skins.length >= 5) o.push(e.skins.filter(s => s.tone && !Array.isArray(s.tone)).map(s => s.emoji));
  return o;
});
await save('emoji.js', Buffer.from('/* Generated by tools/fetch-vendor.mjs from emojibase-data ' + VERSIONS.emojibase + '. [emoji, label, tags, group, shortcodes (space-separated), skinToneVariants?] */\nwindow.QUILLDOWN_EMOJI_GROUPS=' + JSON.stringify(GROUPS) + ';\nwindow.QUILLDOWN_EMOJI=' + JSON.stringify(list) + ';\n'));

await save('VERSIONS.json', Buffer.from(JSON.stringify(VERSIONS, null, 2) + '\n'));
console.log('\nDone — remember to bump CACHE in sw.js if you changed versions.');
