/* Quilldown — regenerates ./sw-assets.js, the pre-cache list used by sw.js.
   Run from the project root after adding, removing or changing files:   node tools/list-assets.mjs
   The version string is a hash of every listed file, so any change makes installed copies update. */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const walk = async (dir) => {
  const out = [];
  for (const e of await readdir(path.join(ROOT, dir), { withFileTypes: true })) {
    const rel = dir + '/' + e.name;
    if (e.isDirectory()) out.push(...await walk(rel)); else out.push(rel);
  }
  return out;
};
const files = ['./', 'index.html', 'manifest.webmanifest',
  ...await walk('css'), ...await walk('js'), ...await walk('icons'), ...await walk('vendor')]
  .filter(f => !/\.(md|map)$/i.test(f) && !/VERSIONS\.json$/.test(f));

const hash = createHash('sha1');
for (const f of files) if (f !== './') hash.update(f).update(await readFile(path.join(ROOT, f)));
const version = hash.digest('hex').slice(0, 10);

await writeFile(path.join(ROOT, 'sw-assets.js'),
  '/* Generated by tools/list-assets.mjs — do not edit. */\n' +
  'self.QUILLDOWN_VERSION = ' + JSON.stringify(version) + ';\n' +
  'self.QUILLDOWN_ASSETS = ' + JSON.stringify(files, null, 1) + ';\n');
console.log(files.length + ' files, version ' + version);
